---
- hosts: all
  become: yes

tasks:
    - name: Installation de Git
      package:
        name: git
        state: latest

    - name: Clonage du repository Golang-myip
      git:
       repo: https://github.com/BastienBalaud/golang-myip.git
       dest: /golang-myip
       clone: yes
       update: yes

    - name: Installation de la commande make
      ansible.builtin.shell:
       cmd: yum install make.x86_64 -y

    - name: Installation du langage Go
      ansible.builtin.shell:
       cmd: yum install golang.x86_64 -y

    - name: Execution du fichier Makefile dans son répertoire
      ansible.builtin.shell:
       cmd: make
       chdir: /golang-myip

    - name: Création du ficher golang-myip.service dans le dossier Temporaire
      ansible.builtin.shell:
       cmd: touch /tmp/golang-myip.service

    - name: Ajout du contenu du service
      shell: |
       echo "[Unit]
       Description=Service système Golang-MyIP

       #Ciblage du service réseau
       After=network.target

       [Service]

       #Sélection du répertoire d'éxécution du fichier
       WorkingDirectory=/golang-myip/
       ExecStart=/golang-myip/build/server.x86_64

       [Install]

       #Installation pour tout les utilisateurs
       WantedBy=multi-user.target" >> /tmp/golang-myip.service

    - name: Déplacement du fichier golang-myip.service dans systemd
      ansible.builtin.shell:
       cmd: mv /tmp/golang-myip.service /etc/systemd/system/

    - name: Changer temporairement le SELinux en Permissive pour activer le service
      ansible.builtin.shell:
       cmd: setenforce 0

    - name: Redémarrage du Daemon système
      ansible.builtin.shell:
       cmd: systemctl daemon-reload

    - name: Démarrage du nouveau service Golang-MyIP
      ansible.builtin.shell:
       cmd: systemctl start golang-myip

    - name: Activation du service Golang-MyIP au démarrage du système
      ansible.builtin.shell:
       cmd: systemctl enable golang-myip

    - name: Téléchargement du package POSIX pour Ansible
      ansible.builtin.shell:
       cmd: yum install ansible-collection-ansible-posix -y

    - name: Rendre le mode Permissive du SELinux permanent
      ansible.posix.selinux:
       policy: targeted
       state: permissive
